baseURL = "https://frankdenneman.github.io/"
languageCode = "en-us"
title = "Frank Denneman"
theme = "PaperMod"

enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"

[params]
  description = "Solving AI Resource Management Challenges in Private Datacenters"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    name = "AI"
    url = "/tags/ai/"
    weight = 30

  [[menu.main]]
    name = "NUMA"
    url = "/tags/numa/"
    weight = 40

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 100
