baseURL = "https://frankdenneman.github.io/"
languageCode = "en-us"
enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

# Anatole as Hugo Module
[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  title = "Frank Denneman"
  author = "Frank Denneman"
  profilePicture = "images/Headshot-FD.jpeg"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    name = "AI"
    url = "/tags/ai/"
    weight = 30

  [[menu.main]]
    name = "NUMA"
    url = "/tags/numa/"
    weight = 40

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 45

  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 50
