# Anatole overlay config

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"

[params]
  title = "Frank Denneman"
  author = "Frank Denneman"
  description = "Frank Denneman"
  profilePicture = "images/Headshot-FD.jpeg"

[taxonomies]
  category = "categories"
  tag = "tags"

# Ensure Anatole is the active theme
theme = "anatole"
